services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
    mongodb: 
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
            - 27017:27017
        volumes: 
            - /data/db
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: gosiabb/auction-svc:latest
        build:
            context: .
            dockerfile: AuctionService/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
            - IdentityServiceUrl=http://identity-svc
        ports: 
            - 5283:80
        depends_on:
            - postgres
            - rabbitmq
    search-svc:
        image: gosiabb/search-svc:latest
        build:
            context: .
            dockerfile: SearchService/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
            - AuctionsServiceUrl=http://auction-svc
        ports: 
            - 5062:80
        depends_on:
            - mongodb
            - rabbitmq
    identity-svc:
        image: gosiabb/identity-svc:latest
        build:
            context: .
            dockerfile: IdentityService/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
        ports: 
            - 5000:80
        depends_on:
            - mongodb
    gateway-svc:
        image: gosiabb/gateway-svc:latest
        build:
            context: .
            dockerfile: GatewayService/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
        ports: 
            - 6001:80
    