apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
    ASPNETCORE_URLS: http://+:82;http://+:7777
    RabbitMq__Host: rabbit-clusterip
    RabbitMq__Username: rabbit
    RabbitMq__Password: rabbitpw
    ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=postgres
    IdentityServiceUrl: http://identity-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
   ASPNETCORE_URLS: http://+:80
   RabbitMq__Host: rabbit-clusterip
   RabbitMq__Username: rabbit
   RabbitMq__PAssword: rabbitpw
   ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
   AuctionsServiceUrl: http://auction-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
   ASPNETCORE_URLS: http://+:80
   IdentityServiceUrl: http://identity-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
     ASPNETCORE_ENVIRONMENT: Docker
     ASPNETCORE_URLS: http://+:80
     ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=identity