name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env: 
            continue: 'false'
        strategy:
            matrix:
                service: 
                 - name: 'gosiabb/auction-svc'
                   path: 'AuctionService'
                 - name: 'gosiabb/search-svc'
                   path: 'SearchService'
                 - name: 'gosiabb/identity-svc'
                   path: 'IdentityService'
                 - name: 'gosiabb/gateway-svc'
                   path: 'GatewayService'
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Checkout for changes in service path
          run: |
            if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
                echo "No changes in ${{matrix.service.path}}. Skipping build"
                echo "continue=false" >> $GITHUB_ENV
            else
                echo "Changes detected on ${{matrix.service.path}}. Proceeding with build"
                echo "continue=true" >> $GITHUB_ENV
            fi

        - name: Set up docker buildx
          if: env.continue == 'true'
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker
          if: env.continue == 'true'
          uses: docker/login-action@v3
          with: 
            username : ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_TOKEN}}

        - name: Build and push dokcer image
          if: env.continue == 'true'
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ${{matrix.service.path}}/Dockerfile
            push: true
            tags: ${{matrix.service.name}}:latest
